#!/usr/bin/env python3
"""Render the skills index into the global AGENTS.md from every SKILL.md's frontmatter.

The SKILL.md `description` is the single source of truth: Claude Code and opencode both
read it to decide when to load a skill, and this index is generated from it, so the
list in AGENTS.md can never drift from the skills on disk.

  index.py            # print the generated blocks
  index.py --write    # replace both blocks between their markers in workstation/config/AGENTS.md
  index.py --check    # exit 1 if the repo-skills block is stale (CI runs this)

Two blocks: the operator's skills (this directory — checked in CI), and third-party
skills installed on THIS machine (~/.claude/skills entries that are not links into this
repo — written by --write, never checked, because CI does not have them).
"""
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
AGENTS = os.path.join(HERE, "..", "..", "config", "AGENTS.md")
BEGIN = "<!-- skills-index:begin (generated by workstation/claude/skills/index.py — do not edit by hand) -->"
END = "<!-- skills-index:end -->"
TP_BEGIN = "<!-- skills-thirdparty:begin (generated by workstation/claude/skills/index.py --write from this machine; not checked in CI) -->"
TP_END = "<!-- skills-thirdparty:end -->"
CLAUDE_SKILLS = os.path.expanduser("~/.claude/skills")


def frontmatter(path):
    text = open(path).read()
    m = re.match(r"^---\n(.*?)\n---\n", text, re.S)
    if not m:
        return None
    fm = {}
    for line in m.group(1).splitlines():
        if ":" in line and not line.startswith(" "):
            k, v = line.split(":", 1)
            fm[k.strip()] = v.strip().strip('"')
    return fm


def split_description(desc):
    """(what, when): the 'Use when/for/to …' sentence is the trigger; the rest is what it does."""
    sentences = re.split(r"(?<=[.!?])\s+(?=[A-Z])", desc)
    when = [s for s in sentences if re.match(r"(Use|Run|Invoke|Trigger)\b", s)]
    what = [s for s in sentences if s not in when]
    return " ".join(what).strip(), " ".join(when).strip()


def _row(name, p):
    fm = frontmatter(p)
    if not fm or "description" not in fm:
        return None
    what, when = split_description(fm["description"])
    cell = lambda s: s.replace("|", "\\|")
    return f"| `{fm.get('name', name)}` | {cell(when) or '—'} | {cell(what)} |"


def render_thirdparty():
    rows = []
    if os.path.isdir(CLAUDE_SKILLS):
        for name in sorted(os.listdir(CLAUDE_SKILLS)):
            d = os.path.join(CLAUDE_SKILLS, name)
            if os.path.realpath(d).startswith(os.path.realpath(HERE) + os.sep):
                continue                      # an operator skill, already in the first block
            p = os.path.join(d, "SKILL.md")
            r = _row(name, p) if os.path.isfile(p) else None
            if r:
                rows.append(r)
    head = ["| Skill | Load it when | What it does |", "|---|---|---|"]
    return "\n".join([TP_BEGIN, ""] + head + rows + ["", TP_END])


def render():
    rows = []
    for name in sorted(os.listdir(HERE)):
        p = os.path.join(HERE, name, "SKILL.md")
        if not os.path.isfile(p):
            continue
        fm = frontmatter(p)
        if not fm or "description" not in fm:
            sys.exit(f"{p}: missing frontmatter description — every skill needs one (it is the trigger)")
        what, when = split_description(fm["description"])
        cell = lambda s: s.replace("|", "\\|")
        rows.append(f"| `{fm.get('name', name)}` | {cell(when) or '—'} | {cell(what)} |")
    head = ["| Skill | Load it when | What it does |", "|---|---|---|"]
    return "\n".join([BEGIN, ""] + head + rows + ["", END])


def main():
    block = render()
    mode = sys.argv[1] if len(sys.argv) > 1 else ""
    if not mode:
        print(block + "\n\n" + render_thirdparty())
        return 0
    text = open(AGENTS).read()
    if BEGIN not in text or END not in text:
        sys.exit(f"markers not found in {AGENTS}; add them where the index should go")
    current = text[text.index(BEGIN):text.index(END) + len(END)]
    if mode == "--check":
        if current != block:
            print("skills index in AGENTS.md is STALE — run: python3 workstation/claude/skills/index.py --write")
            return 1
        print("skills index up to date")
        return 0
    if mode == "--write":
        text = text.replace(current, block)
        tp = render_thirdparty()
        if TP_BEGIN in text and TP_END in text:
            old = text[text.index(TP_BEGIN):text.index(TP_END) + len(TP_END)]
            text = text.replace(old, tp)
        open(AGENTS, "w").write(text)
        print(f"wrote skills index ({block.count(chr(10) + '| `')} repo skills, "
              f"{tp.count(chr(10) + '| `')} third-party) into {os.path.relpath(AGENTS)}")
        return 0
    sys.exit("usage: index.py [--write | --check]")


if __name__ == "__main__":
    sys.exit(main())
