"""Contract test — the worker validated against the VENDORED seam schema + golden fixtures
(schema/, synced from the app repo). Mirrors the app-side test_delivery_envelope_contract
so the two tracks cannot drift. If a golden fixture fails to render, the contract moved —
align the worker, don't edit the vendored copy."""

from __future__ import annotations

import json
from pathlib import Path

import pytest
from jsonschema import Draft202012Validator

from delivery.envelope import Channel, DeliveryEnvelope
from delivery.render import Renderer
from delivery.tenant import load_registry

_ROOT = Path(__file__).resolve().parent.parent
_SCHEMA_DIR = _ROOT / "schema" / "podcast"
_FIXTURES = _SCHEMA_DIR / "fixtures"
_TENANTS = load_registry(str(_ROOT / "tenants.yaml"), env={}, root=_ROOT)


def _schema() -> dict:
    return json.loads((_SCHEMA_DIR / "delivery-envelope.schema.json").read_text())


def _fixture(name: str) -> dict:
    return json.loads((_FIXTURES / name).read_text())


def _renderer() -> Renderer:
    return Renderer.for_tenant(_TENANTS["podcast"])


ALL_FIXTURES = [
    "your-week-digest.v1.golden.json",
    "resurface-nudge.v1.golden.json",
    "daily-recap.v1.golden.json",
    "recommendations-digest.v1.golden.json",
    # Generated by the app's real builder (podcast_scraper test_new_episodes_envelope_golden.py).
    # Its absence is why a template reading a field the app never sends went unnoticed for 33 h.
    "new-episodes.v1.golden.json",
]


def test_every_vendored_fixture_is_exercised():
    """A fixture vendored but missing from ALL_FIXTURES is validated, parsed and rendered by
    nothing — the gap the new-episodes outage fell through. Keep the list and the dir in step."""
    vendored = {p.name for p in _FIXTURES.glob("*.golden.json")}
    # magic-link has its own tests below: it carries no consent_snapshot, by design.
    assert vendored - {"magic-link.v1.golden.json"} == set(ALL_FIXTURES)


def test_new_episodes_golden_renders_email_with_graph_chips():
    """The golden is exactly what the app sends: no podcast_title, graph_refs on every episode."""
    env = DeliveryEnvelope.from_dict(_fixture("new-episodes.v1.golden.json"))
    html = _renderer().render_email(env).html
    payload = _fixture("new-episodes.v1.golden.json")["payload"]
    assert f"{payload['count']} new episodes are out" in html
    for ep in payload["episodes"]:
        assert ep["episode_title"] in html
        assert "https://closelistening.app" + ep["deep_link"] in html
        for ref in ep["graph_refs"]:
            assert ref["label"] in html  # carried as chips (moat rule), like the digest
    assert "unsubscribe" in html.lower()


@pytest.mark.parametrize("name", ALL_FIXTURES)
def test_fixture_matches_vendored_schema(name):
    Draft202012Validator(_schema()).validate(_fixture(name))  # raises if the fixture drifts


@pytest.mark.parametrize("name", ALL_FIXTURES)
def test_worker_parses_fixture(name):
    env = DeliveryEnvelope.from_dict(_fixture(name))
    assert env.id
    assert env.consent_snapshot.unsubscribe_ref  # the ref (not token) the worker embeds


def test_digest_fixture_renders_email():
    env = DeliveryEnvelope.from_dict(_fixture("your-week-digest.v1.golden.json"))
    assert env.channel is Channel.EMAIL
    html = _renderer().render_email(env).html
    # graph_refs carried as chips (moat rule); relative deep_links absolutised; ref unsubscribe.
    assert "Jensen Huang" in html and "AI Safety" in html
    assert "https://closelistening.app/episode/" in html
    assert "ref=example-unsubscribe-ref" in html
    assert "&lt;" not in html.split("<body")[0]  # sanity: head not double-escaped


def test_nudge_fixture_renders_push():
    env = DeliveryEnvelope.from_dict(_fixture("resurface-nudge.v1.golden.json"))
    assert env.channel is Channel.PUSH
    push = _renderer().render_push(env)
    assert push.title
    assert push.url.startswith("https://closelistening.app/")  # relative → absolutised
    assert push.tag == "resurface-nudge"


def test_nudge_fixture_also_renders_email():
    # A nudge can go by email too; ensure the email template handles payload.lead.
    env = DeliveryEnvelope.from_dict(_fixture("resurface-nudge.v1.golden.json"))
    html = _renderer().render_email(env).html
    assert "Jensen Huang" in html
    assert "ref=example-unsubscribe-ref" in html


def test_daily_recap_fixture_renders_email():
    # RFC-122 #2039 — a single-episode day renders the FULL recap.
    env = DeliveryEnvelope.from_dict(_fixture("daily-recap.v1.golden.json"))
    assert env.channel is Channel.EMAIL
    rendered = _renderer().render_email(env)
    assert rendered.subject == "Your recap · NVIDIA: The Machine That Makes the Machine"
    html = rendered.html
    assert "NVIDIA: The Machine That Makes the Machine" in html
    assert "The bottleneck was never compute" in html  # a key point
    assert "the real product" in html and "Jensen Huang" in html  # signature quote + speaker
    assert "Vertical integration" in html  # a top insight
    assert "Scaling Laws" in html  # topic chip
    assert "semiconductor supply chain" in html  # storyline
    assert "https://closelistening.app/episode/acquired-nvidia" in html  # deep link absolutised
    # The one-click unsubscribe is TYPE-AWARE — it silences the recap, not the weekly digest.
    # (The `&` is HTML-escaped to `&amp;` in the href — correct; the client unescapes it.)
    assert "ref=example-unsubscribe-ref" in html and "type=daily_recap" in html


def test_daily_recap_many_renders_compact_stack():
    # A multi-episode day renders the compact per-episode stack (built inline; the golden is count=1).
    base = _fixture("daily-recap.v1.golden.json")
    ep = base["payload"]["episodes"][0]
    base["payload"] = {
        "day": "2026-09-11",
        "count": 2,
        "episodes": [ep, {**ep, "title": "TSMC (Part II)", "deep_link": "/episode/tsmc-part-ii"}],
    }
    rendered = _renderer().render_email(DeliveryEnvelope.from_dict(base))
    assert rendered.subject == "Your day, recapped · 2 episodes"
    assert "TSMC (Part II)" in rendered.html
    assert "Open in Close Listening" in rendered.html  # the compact-stack per-episode CTA


def test_recommendations_fixture_renders_email():
    # wave-H monthly discovery digest — reuses the sections shape; must now render (was never sent).
    env = DeliveryEnvelope.from_dict(_fixture("recommendations-digest.v1.golden.json"))
    assert env.channel is Channel.EMAIL
    rendered = _renderer().render_email(env)
    assert "New for you" in rendered.html
    assert "New in what you follow" in rendered.html  # the new_in_interests section label
    assert "TSMC (Part II)" in rendered.html
    assert "https://closelistening.app/episode/" in rendered.html
    assert "Semiconductors" in rendered.html  # a graph_ref chip
    assert "September 2026" in rendered.subject  # monthly period label


# --- transactional envelopes (app-side #2272) -------------------------------------------------


def test_auth_link_envelope_parses_without_a_consent_snapshot() -> None:
    """A sign-in link has no account behind it, so it carries no consent snapshot.

    This used to raise KeyError before it could reach a template: `ConsentSnapshot.from_dict` read
    `d["unsubscribe_ref"]` directly while its two siblings used `.get` with defaults, so an absent
    snapshot was a hard parse failure rather than an absent snapshot.
    """
    import json
    from pathlib import Path

    from delivery.envelope import DeliveryEnvelope

    fixture = Path(__file__).resolve().parents[1] / "schema/podcast/fixtures/magic-link.v1.golden.json"
    env = DeliveryEnvelope.from_dict(json.loads(fixture.read_text()))
    assert env.consent_snapshot is None
    assert env.type == "auth_link"
    assert env.user_id == ""  # the schema requires exactly this for auth


def test_magic_link_email_renders_and_carries_no_unsubscribe() -> None:
    """The one template that must NOT offer an unsubscribe link.

    Every notification template ends with one. You cannot unsubscribe from being able to log in, and
    an auth envelope has no `unsubscribe_ref` to build the link from — so a footer here would render
    a dead URL into a real inbox.
    """
    import json
    from pathlib import Path

    from delivery.envelope import DeliveryEnvelope
    from delivery.render import Renderer

    root = Path(__file__).resolve().parents[1]
    env = DeliveryEnvelope.from_dict(
        json.loads((root / "schema/podcast/fixtures/magic-link.v1.golden.json").read_text())
    )
    rendered = Renderer(
        root / "delivery/templates/podcast", app_origin="https://closelistening.app"
    ).render_email(env)

    assert rendered.subject
    assert env.payload["link"] in rendered.html, "the sign-in link must reach the body"
    assert "unsubscribe" not in rendered.html.lower()
    # The one line that tells a person who did NOT request it that ignoring it is safe.
    assert "was not you" in rendered.html


def test_new_episodes_email_renders_without_podcast_title() -> None:
    """The app's new-episodes payload carries no `podcast_title` (the seam schema does not
    define it). The renderer is StrictUndefined, so `{% if ep.podcast_title %}` raised on every
    real envelope: from 2026-10-02 06:02Z every drain aborted on it and no email went out.
    The episode shape here is the one the live outbox served on 2026-10-03."""
    from delivery.render import Renderer

    from conftest import make_envelope

    root = Path(__file__).resolve().parents[1]
    episodes = [
        {"episode_slug": f"ep-{i}", "episode_title": f"Episode {i}", "deep_link": f"/episode/ep-{i}",
         "graph_refs": []}
        for i in range(1, 4)
    ]
    env = make_envelope(id="newep_test", template="new-episodes.v1",
                        payload={"count": 3, "episodes": episodes, "slugs": [e["episode_slug"] for e in episodes]})
    rendered = Renderer(
        root / "delivery/templates/podcast", app_origin="https://closelistening.app"
    ).render_email(env)
    assert "3 new episodes are out" in rendered.html
    for e in episodes:
        assert e["episode_title"] in rendered.html
        assert "https://closelistening.app" + e["deep_link"] in rendered.html


# --- every link in an email opens the same thing the app's own links do (operator 2026-10-05) ---
#
# The chips stripped the graph id's prefix — /topic/ai-safety?scope=mine for topic:ai-safety — and
# the app's topic/person pages resolve `topic:x`, never a bare `x`, so every chip opened an empty
# page. They now carry the full id, percent-encoded: the exact link the app's "Copy link" builds,
# which is also what the installed app claims (Universal Links / App Links) — so a tap opens the
# app on that page, or the browser when the app is not installed.

_APP_PATHS = ("episode", "podcast", "topic", "person", "storyline", "theme", "profile")


@pytest.mark.parametrize(
    "name",
    [
        "your-week-digest.v1.golden.json",
        "recommendations-digest.v1.golden.json",
        "resurface-nudge.v1.golden.json",
        "daily-recap.v1.golden.json",
        "new-episodes.v1.golden.json",
    ],
)
def test_email_links_are_app_links_with_full_graph_ids(name):
    import re
    from urllib.parse import unquote, urlsplit

    env = DeliveryEnvelope.from_dict(_fixture(name))
    if env.channel is not Channel.EMAIL:
        pytest.skip("push-only fixture")
    html = _renderer().render_email(env).html
    hrefs = [h.replace("&amp;", "&") for h in re.findall(r'href="([^"]+)"', html)]
    content = [h for h in hrefs if "/api/" not in h]  # unsubscribe is a server route
    assert content, f"{name}: no content links rendered — the check would pass vacuously"
    for href in content:
        parts = urlsplit(href)
        assert parts.netloc == "closelistening.app", href
        kind, _, ident = parts.path.lstrip("/").partition("/")
        assert kind in _APP_PATHS, f"{href}: /{kind} is not a page the app opens"
        assert "scope=" not in parts.query, f"{href}: the app ignores ?scope="
        if kind in ("topic", "person"):
            assert unquote(ident).startswith(f"{kind}:"), f"{href}: stripped graph id"
        if kind == "storyline":
            assert unquote(ident).startswith("topic:"), f"{href}: a storyline link takes its anchor topic"


def test_push_fallback_url_is_the_revisit_screen():
    # `/revisit` is not an app route; the app sends unknown paths to Home.
    for name in ("resurface-nudge.v1.json.j2", "your-week-digest.v1.json.j2"):
        src = (Path(__file__).resolve().parents[1] / "delivery" / "templates" / "podcast" / "push" / name).read_text()
        assert "default('/revisit')" not in src and "/library?tab=revisit" in src, name


# --- which links people click in our emails (operator 2026-10-05) ---------------------------------
#
# Every content link carries utm_source=email, which email, and what kind of page; the app reports
# `email_link_opened` to Umami on arrival. Our own tags rather than Resend's click tracking, which
# would bounce the tap through another host and stop the phone opening the installed app.

_EMAILS = {
    "your-week-digest.v1.golden.json": "your_week_digest",
    "recommendations-digest.v1.golden.json": "recommendations_digest",
    "resurface-nudge.v1.golden.json": "resurface_nudge",
    "daily-recap.v1.golden.json": "daily_recap",
    "new-episodes.v1.golden.json": "new_episodes",
}


@pytest.mark.parametrize("name,campaign", sorted(_EMAILS.items()))
def test_every_content_link_says_which_email_it_came_from(name, campaign):
    import re
    from urllib.parse import parse_qs, urlsplit

    env = DeliveryEnvelope.from_dict(_fixture(name))
    if env.channel is not Channel.EMAIL:
        pytest.skip("push-only fixture")
    html = _renderer().render_email(env).html
    hrefs = [h.replace("&amp;", "&") for h in re.findall(r'href="([^"]+)"', html)]
    content = [h for h in hrefs if "/api/" not in h]
    assert content
    for href in content:
        parts = urlsplit(href)
        q = parse_qs(parts.query)
        kind = parts.path.lstrip("/").split("/", 1)[0]
        assert q.get("utm_source") == ["email"], href
        assert q.get("utm_campaign") == [campaign], href
        assert q.get("utm_content") == [kind], href
        assert not any(k for k in q if k not in {"utm_source", "utm_campaign", "utm_content", "t", "revisit", "tab"}), href
    for href in hrefs:
        if "/api/" in href:
            assert "utm_" not in href, f"{href}: server links (unsubscribe) are not tagged"


def test_the_sign_in_email_is_not_tagged():
    env = DeliveryEnvelope.from_dict(_fixture("magic-link.v1.golden.json"))
    html = _renderer().render_email(env).html
    assert "utm_" not in html


def test_tagging_keeps_the_moment_and_does_not_double_tag():
    r = _renderer()
    out = r.tag_links(
        '<a href="https://closelistening.app/episode/x?t=65&amp;utm_source=old">x</a>', "daily_recap"
    )
    assert (
        'href="https://closelistening.app/episode/x?t=65&amp;utm_source=email'
        '&amp;utm_campaign=daily_recap&amp;utm_content=episode"'
    ) in out
    other = '<a href="https://example.com/episode/x">x</a>'
    assert r.tag_links(other, "daily_recap") == other


@pytest.mark.parametrize(
    "name",
    [
        "your-week-digest.v1.golden.json",
        "recommendations-digest.v1.golden.json",
        "daily-recap.v1.golden.json",
        "new-episodes.v1.golden.json",
        "magic-link.v1.golden.json",
    ],
)
def test_every_email_carries_the_app_brand_lockup(name):
    # operator 2026-10-05: the emails looked unbranded next to the app. One partial
    # (email/_brand.html.j2): the waveform mark (PNG — email clients do not render SVG) served from
    # the tenant's own origin, the tagline, and the wordmark as REAL text, so a client that blocks
    # images still shows the brand.
    env = DeliveryEnvelope.from_dict(_fixture(name))
    if env.channel is not Channel.EMAIL:
        pytest.skip("push-only fixture")
    html = _renderer().render_email(env).html
    assert 'src="https://closelistening.app/brand/email-mark.png"' in html
    assert "Listen. Understand. Remember." in html
    assert ">Close Listening</div>" in html
    # One footer for every email; the unsubscribe + settings links only where there is consent to
    # withdraw — the sign-in email is transactional.
    assert "Close Listening · Listen. Understand. Remember." in html
    transactional = name.startswith("magic-link")
    assert ("Manage notifications" in html) is not transactional
    assert ("Unsubscribe" in html) is not transactional


# --- the app's episode header, Play from, and the inbox preview line (operator 2026-10-05) -------


def test_display_filters():
    from delivery.render import _clock, _duration, _pubdate

    assert _clock(725) == "12:05" and _clock(3921) == "1:05:21" and _clock("x") == ""
    assert _duration(2520) == "42 min" and _duration(3900) == "1 h 5 min" and _duration(7200) == "2 h"
    assert _duration(None) == "" and _duration(0) == ""
    assert _pubdate("2026-09-21") == "Sep 21, 2026" and _pubdate("garbage") == ""


def test_an_episode_item_reads_like_the_app():
    html = _renderer().render_email(
        DeliveryEnvelope.from_dict(_fixture("your-week-digest.v1.golden.json"))
    ).html
    # artwork made absolute against the tenant origin (the edge serves it without a session)
    assert 'src="https://closelistening.app/api/app/artwork?ref=acquired%2Fnvidia.jpg&amp;size=thumb"' in html
    assert ">Acquired</div>" in html  # the show, above the title
    assert "3 h 39 min · Sep 21, 2026" in html
    # the saved moment plays from where it was saved — the app's PlayFrom control
    assert "▶ Play from 1:05:21" in html


@pytest.mark.parametrize(
    "name,starts",
    [
        ("your-week-digest.v1.golden.json", "Your weekly Close Listening:"),
        ("recommendations-digest.v1.golden.json", "Picked for you this month:"),
        ("daily-recap.v1.golden.json", "Notes on "),
        ("new-episodes.v1.golden.json", "New from Show fa and 1 more"),
        ("magic-link.v1.golden.json", "Your sign-in link for Close Listening"),
    ],
)
def test_every_email_sets_its_inbox_preview_line(name, starts):
    import re

    html = _renderer().render_email(DeliveryEnvelope.from_dict(_fixture(name))).html
    hidden = re.search(r'<div style="display:none;[^"]*">([^<&]*)', html)
    assert hidden, f"{name}: no hidden preview line"
    assert hidden.group(1).startswith(starts), hidden.group(1)


def test_a_topic_item_is_not_dressed_as_an_episode():
    # Trending items link to the TOPIC; they get no artwork or episode meta line.
    html = _renderer().render_email(
        DeliveryEnvelope.from_dict(_fixture("recommendations-digest.v1.golden.json"))
    ).html
    assert "/api/app/artwork" not in html


def test_an_episode_without_artwork_still_gets_its_artwork_column():
    # operator 2026-10-05: artwork next to every episode name. With none anywhere, the app's
    # placeholder tile (the brand mark on the raised panel) holds the column; a topic link gets none.
    html = _renderer().render_email(
        DeliveryEnvelope.from_dict(_fixture("new-episodes.v1.golden.json"))
    ).html
    episodes = html.count('href="https://closelistening.app/episode/')
    tiles = html.count('width="23" height="24"')
    assert tiles == 2, f"{tiles} placeholder tiles for 2 artwork-less episodes ({episodes} links)"
    # Your Week mixes episode items (one with artwork) and a topic item (trending): a tile for each
    # artwork-less EPISODE, none for the topic, the real image for the one that has it.
    wk = _fixture("your-week-digest.v1.golden.json")
    items = [i for sec in wk["payload"]["sections"] for i in sec["items"]]
    bare = [i for i in items if i["deep_link"].startswith("/episode/") and not i.get("artwork_url")]
    assert any(not i["deep_link"].startswith("/episode/") for i in items), "no topic item: vacuous"
    wk_html = _renderer().render_email(DeliveryEnvelope.from_dict(wk)).html
    assert wk_html.count('width="23" height="24"') == len(bare)
